In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from torch.utils.data import ConcatDataset, DataLoader

import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

from utils.EEDDataLoader import EEGDataset
from utils.train_eval import eval, train
from models.ConvParallelEEG1DModel import ConvParallelEEG1DModel

files_list_csv = "./dataset/meta_data.csv"
train_data_csv = "./dataset/train.csv"
val_data_csv = "./dataset/eval.csv"
test_data_csv = "./dataset/test.csv"
prediction_saving_csv_train = "./dataset/predictions/predictions_train_conv_crops.csv"
prediction_saving_csv_eval = "./dataset/predictions/predictions_eval_conv_crops.csv"
prediction_saving_csv_test = "./dataset/predictions/predictions_test_conv_crops.csv"
model_saving_name = "./dataset/model/weights/conv_tt_0_original.pt"

epochs = 20
batch_size = 64
hidden_size = 20
output_size = 3  # Binary classification
number_of_eeg_channels = 1
eval_batch = 1
threshold = 0.495
active_branches = [0,1]

/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
train_dataset = EEGDataset(train_data_csv, number_of_eeg_channels=number_of_eeg_channels)
val_dataset = EEGDataset(val_data_csv, number_of_eeg_channels=number_of_eeg_channels)
test_dataset = EEGDataset(test_data_csv, number_of_eeg_channels=number_of_eeg_channels)
combined_dataset = ConcatDataset([train_dataset, val_dataset])

# Split the data into training and validation sets
# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)#, collate_fn=collate)
train_loader = DataLoader(combined_dataset, batch_size=batch_size, shuffle=True)#, collate_fn=collate)

val_loader = DataLoader(val_dataset, batch_size=eval_batch, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=eval_batch, shuffle=False)

In [3]:
input = train_dataset.__getitem__(0)
input_x1 = input[1].shape
input_x2 = input[2].shape
input_x3 = input[3].shape
criterion = nn.CrossEntropyLoss()

loss_fn = nn.CrossEntropyLoss(label_smoothing=0.1)

print(input_x1,input_x2,input_x3)
input_channels_list = [input_x1[1], input_x2[1], input_x3[1]]

model = ConvParallelEEG1DModel(input_channels_list=input_channels_list, output_size=3)

main_output, aux_outputs = model([input[1], input[2], input[3]], active_branch_indices=active_branches)
print("Output shape:", main_output.shape) 

optimizer = torch.optim.AdamW(model.parameters(), lr=0.0001,betas=(0.9, 0.98), eps=1e-9, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3, factor=0.5)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:57: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at ../aten/src/ATen/native/Copy.cpp:305.)
  coefficients_cmor = torch.tensor(coefficients_cmor, dtype=torch.float32)
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)


torch.Size([1, 1, 400]) torch.Size([1, 33, 14]) torch.Size([1, 30, 400])
Output shape: torch.Size([1, 3])


ConvParallelEEG1DModel(
  (branches): ModuleList(
    (0): ConvBranch1D(
      (conv): Sequential(
        (0): Conv1d(1, 32, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
        (3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
        (4): Dropout(p=0.3, inplace=False)
      )
      (global_pool): AdaptiveAvgPool1d(output_size=1)
      (linear): Linear(in_features=32, out_features=3, bias=True)
    )
    (1): ConvBranch1D(
      (conv): Sequential(
        (0): Conv1d(33, 32, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
        (3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
        (4): Dropout(p=0.3, inplace=False)
      )
      (global_pool): AdaptiveAvgPool1d(output_size=1)
      (linear): Linear(

In [4]:
prev_eval_loss = 0
prev_eval_acc = 0


In [5]:
model = model.to(device)

prev_eval_loss, prev_eval_acc = eval(model, val_loader, loss_fn, 1,False,'', active_branches, device)
print("Loss:",prev_eval_loss, "Accuracy",prev_eval_acc)

Eval:   0%|          | 0/43343 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'


/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 43343/43343 [03:06<00:00, 232.51it/s]

Correct classified: 5849.0 / 43343
Class-wise correct: Class 0 = 0.0, Class 1 = 0.0, Class 2 = 5849.0
Precision: 4.50  Recall: 33.33  F1: 7.93
Confusion Matrix:
 [[    0     0 22538]
 [    0     0 14956]
 [    0     0  5849]]
Loss: 1.1518479723358612 Accuracy 0.1349468195556376



/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
result = {"epoch":[],"train_loss":[],"train_acc":[],"eval_loss":[],"eval_acc":[],"test_acc":[],"test_loss":[]}
saved_epoch = 0

In [7]:
for epoch in range(epochs):  # loop over the dataset multiple times
    train_loss, train_acc = train(model, train_loader,optimizer, loss_fn, active_branches, device)
    print(f"Train Loss after epoch {epoch+2}: {train_loss} Train ACC after epoch {epoch}: {train_acc}")
    eval_loss, eval_acc = eval(model, test_loader, loss_fn, eval_batch,False,'', active_branches, device)
    print(f"VAL Loss after epoch {epoch}: {eval_loss} VAL ACC after epoch {epoch}: {eval_acc}")
    # test_loss, test_acc = eval(model, test_loader, loss_fn, eval_batch,False,'', active_branches, device)
    test_loss = eval_loss
    test_acc = eval_acc
    print(f"Test Loss after epoch {epoch}: {test_loss} Test Acc after epoch {epoch}: {test_acc}")

    scheduler.step(eval_loss)
    
    result['epoch'].append(epoch)
    
    result['train_loss'].append(train_loss)
    result['train_acc'].append(train_acc)
    result['eval_loss'].append(eval_loss)
    result['eval_acc'].append(eval_acc)
    result['test_loss'].append(test_loss)
    result['test_acc'].append(test_acc)

    if prev_eval_acc < eval_acc:
      prev_eval_acc = eval_acc
      saved_epoch = epoch
      torch.save(model.state_dict(), model_saving_name)
      print("WEIGHTS SAVED")

Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)


Training: 100%|██████████| 4531/4531 [11:09<00:00,  6.76it/s]


Correct Classified: 188902.0 / 289972
Class-wise correct: Class 0 = 118856.0, Class 1 = 23504.0, Class 2 = 46542.0
Train Loss after epoch 2: 1.7260208891285778 Train ACC after epoch 0: 0.6514491054308692


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:26<00:00, 280.82it/s]


Correct classified: 54200.0 / 74774
Class-wise correct: Class 0 = 31557.0, Class 1 = 8154.0, Class 2 = 14489.0
Precision: 68.16  Recall: 68.69  F1: 68.24
Confusion Matrix:
 [[31557  1442  3564]
 [ 1437  8154  3581]
 [ 5410  5140 14489]]
VAL Loss after epoch 0: 0.7670723067209797 VAL ACC after epoch 0: 0.7248508839971113
Test Loss after epoch 0: 0.7670723067209797 Test Acc after epoch 0: 0.7248508839971113
WEIGHTS SAVED


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:05<00:00,  6.81it/s]


Correct Classified: 210783.0 / 289972
Class-wise correct: Class 0 = 119375.0, Class 1 = 32073.0, Class 2 = 59335.0
Train Loss after epoch 3: 1.5908155940642448 Train ACC after epoch 1: 0.7269081152663016


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:29<00:00, 277.55it/s]


Correct classified: 56335.0 / 74774
Class-wise correct: Class 0 = 31418.0, Class 1 = 8648.0, Class 2 = 16269.0
Precision: 70.92  Recall: 72.19  F1: 71.34
Confusion Matrix:
 [[31418  1622  3523]
 [ 1329  8648  3195]
 [ 3176  5594 16269]]
VAL Loss after epoch 1: 0.7135739833962287 VAL ACC after epoch 1: 0.7534035894829754
Test Loss after epoch 1: 0.7135739833962287 Test Acc after epoch 1: 0.7534035894829754
WEIGHTS SAVED


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:21<00:00,  6.65it/s]


Correct Classified: 216899.0 / 289972
Class-wise correct: Class 0 = 119751.0, Class 1 = 35221.0, Class 2 = 61927.0
Train Loss after epoch 4: 1.5565125984851953 Train ACC after epoch 2: 0.7479998068779055


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [05:35<00:00, 222.61it/s]


Correct classified: 57737.0 / 74774
Class-wise correct: Class 0 = 31483.0, Class 1 = 9449.0, Class 2 = 16805.0
Precision: 73.12  Recall: 74.99  F1: 73.57
Confusion Matrix:
 [[31483  1879  3201]
 [ 1280  9449  2443]
 [ 2231  6003 16805]]
VAL Loss after epoch 2: 0.6948183821042198 VAL ACC after epoch 2: 0.7721534223125686
Test Loss after epoch 2: 0.6948183821042198 Test Acc after epoch 2: 0.7721534223125686
WEIGHTS SAVED


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [12:06<00:00,  6.24it/s]


Correct Classified: 220193.0 / 289972
Class-wise correct: Class 0 = 120482.0, Class 1 = 36650.0, Class 2 = 63061.0
Train Loss after epoch 5: 1.5379551311540067 Train ACC after epoch 3: 0.75935952436787


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:22<00:00, 284.71it/s]


Correct classified: 57568.0 / 74774
Class-wise correct: Class 0 = 31073.0, Class 1 = 8770.0, Class 2 = 17725.0
Precision: 72.55  Recall: 74.12  F1: 73.08
Confusion Matrix:
 [[31073  1949  3541]
 [ 1030  8770  3372]
 [ 1847  5467 17725]]
VAL Loss after epoch 3: 0.6906158838526826 VAL ACC after epoch 3: 0.7698932784122824
Test Loss after epoch 3: 0.6906158838526826 Test Acc after epoch 3: 0.7698932784122824


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:24<00:00,  6.62it/s]


Correct Classified: 222407.0 / 289972
Class-wise correct: Class 0 = 121188.0, Class 1 = 37967.0, Class 2 = 63252.0
Train Loss after epoch 6: 1.5248508161594472 Train ACC after epoch 4: 0.7669947443201413


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:53<00:00, 254.46it/s]


Correct classified: 57432.0 / 74774
Class-wise correct: Class 0 = 32570.0, Class 1 = 9774.0, Class 2 = 15088.0
Precision: 73.32  Recall: 74.51  F1: 72.87
Confusion Matrix:
 [[32570  1900  2093]
 [ 1714  9774  1684]
 [ 3251  6700 15088]]
VAL Loss after epoch 4: 0.6905913419630342 VAL ACC after epoch 4: 0.7680744643860166
Test Loss after epoch 4: 0.6905913419630342 Test Acc after epoch 4: 0.7680744643860166


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:06<00:00,  6.80it/s]


Correct Classified: 223544.0 / 289972
Class-wise correct: Class 0 = 121640.0, Class 1 = 38676.0, Class 2 = 63228.0
Train Loss after epoch 7: 1.5150250786583672 Train ACC after epoch 5: 0.7709158125612128


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:01<00:00, 309.42it/s]


Correct classified: 58289.0 / 74774
Class-wise correct: Class 0 = 31887.0, Class 1 = 8956.0, Class 2 = 17446.0
Precision: 73.49  Recall: 74.96  F1: 73.92
Confusion Matrix:
 [[31887  1737  2939]
 [ 1501  8956  2715]
 [ 1785  5808 17446]]
VAL Loss after epoch 5: 0.6722244736536854 VAL ACC after epoch 5: 0.7795356674780004
Test Loss after epoch 5: 0.6722244736536854 Test Acc after epoch 5: 0.7795356674780004
WEIGHTS SAVED


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:39<00:00,  7.09it/s]


Correct Classified: 224614.0 / 289972
Class-wise correct: Class 0 = 121912.0, Class 1 = 39127.0, Class 2 = 63575.0
Train Loss after epoch 8: 1.5071563393673448 Train ACC after epoch 6: 0.7746058240105941


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:00<00:00, 311.24it/s]


Correct classified: 57860.0 / 74774
Class-wise correct: Class 0 = 31753.0, Class 1 = 8122.0, Class 2 = 17985.0
Precision: 72.47  Recall: 73.44  F1: 72.85
Confusion Matrix:
 [[31753  1636  3174]
 [ 1407  8122  3643]
 [ 1755  5299 17985]]
VAL Loss after epoch 6: 0.6668107484041087 VAL ACC after epoch 6: 0.7737983791157355
Test Loss after epoch 6: 0.6668107484041087 Test Acc after epoch 6: 0.7737983791157355


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:40<00:00,  7.08it/s]


Correct Classified: 225496.0 / 289972
Class-wise correct: Class 0 = 122261.0, Class 1 = 39623.0, Class 2 = 63612.0
Train Loss after epoch 9: 1.5013121196803234 Train ACC after epoch 7: 0.7776474969997104


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [03:59<00:00, 311.76it/s]


Correct classified: 58540.0 / 74774
Class-wise correct: Class 0 = 31650.0, Class 1 = 9547.0, Class 2 = 17343.0
Precision: 74.12  Recall: 76.10  F1: 74.53
Confusion Matrix:
 [[31650  2086  2827]
 [ 1105  9547  2520]
 [ 1429  6267 17343]]
VAL Loss after epoch 7: 0.6690685703768965 VAL ACC after epoch 7: 0.7828924492470645
Test Loss after epoch 7: 0.6690685703768965 Test Acc after epoch 7: 0.7828924492470645
WEIGHTS SAVED


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:39<00:00,  7.09it/s]


Correct Classified: 226214.0 / 289972
Class-wise correct: Class 0 = 122339.0, Class 1 = 40159.0, Class 2 = 63716.0
Train Loss after epoch 10: 1.4959016711578756 Train ACC after epoch 8: 0.7801235981405101


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:00<00:00, 311.17it/s]


Correct classified: 58364.0 / 74774
Class-wise correct: Class 0 = 31914.0, Class 1 = 9732.0, Class 2 = 16718.0
Precision: 74.08  Recall: 75.98  F1: 74.28
Confusion Matrix:
 [[31914  2064  2585]
 [ 1338  9732  2102]
 [ 1679  6642 16718]]
VAL Loss after epoch 8: 0.6748594169728361 VAL ACC after epoch 8: 0.7805386899189558
Test Loss after epoch 8: 0.6748594169728361 Test Acc after epoch 8: 0.7805386899189558


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:36<00:00,  7.11it/s]


Correct Classified: 226846.0 / 289972
Class-wise correct: Class 0 = 122421.0, Class 1 = 40350.0, Class 2 = 64075.0
Train Loss after epoch 11: 1.4921823515320582 Train ACC after epoch 9: 0.7823031189218269


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:00<00:00, 311.49it/s]


Correct classified: 57889.0 / 74774
Class-wise correct: Class 0 = 32928.0, Class 1 = 9534.0, Class 2 = 15427.0
Precision: 73.72  Recall: 74.68  F1: 73.31
Confusion Matrix:
 [[32928  1780  1855]
 [ 1758  9534  1880]
 [ 3127  6485 15427]]
VAL Loss after epoch 9: 0.6823263012699193 VAL ACC after epoch 9: 0.7741862144595715
Test Loss after epoch 9: 0.6823263012699193 Test Acc after epoch 9: 0.7741862144595715


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:36<00:00,  7.12it/s]


Correct Classified: 227477.0 / 289972
Class-wise correct: Class 0 = 122535.0, Class 1 = 40729.0, Class 2 = 64213.0
Train Loss after epoch 12: 1.487429340610281 Train ACC after epoch 10: 0.7844791910943125


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:20<00:00, 286.57it/s]


Correct classified: 57596.0 / 74774
Class-wise correct: Class 0 = 32278.0, Class 1 = 8638.0, Class 2 = 16680.0
Precision: 72.27  Recall: 73.49  F1: 72.51
Confusion Matrix:
 [[32278  1810  2475]
 [ 1495  8638  3039]
 [ 2052  6307 16680]]
VAL Loss after epoch 10: 0.6755771954384288 VAL ACC after epoch 10: 0.7702677401235724
Test Loss after epoch 10: 0.6755771954384288 Test Acc after epoch 10: 0.7702677401235724


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:17<00:00,  6.69it/s]


Correct Classified: 228096.0 / 289972
Class-wise correct: Class 0 = 122605.0, Class 1 = 41082.0, Class 2 = 64409.0
Train Loss after epoch 13: 1.485036741000773 Train ACC after epoch 11: 0.7866138799608238


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:20<00:00, 287.47it/s]


Correct classified: 57848.0 / 74774
Class-wise correct: Class 0 = 32369.0, Class 1 = 8919.0, Class 2 = 16560.0
Precision: 72.81  Recall: 74.13  F1: 73.00
Confusion Matrix:
 [[32369  1804  2390]
 [ 1530  8919  2723]
 [ 2032  6447 16560]]
VAL Loss after epoch 11: 0.6722298010796732 VAL ACC after epoch 11: 0.7736378955251826
Test Loss after epoch 11: 0.6722298010796732 Test Acc after epoch 11: 0.7736378955251826


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:46<00:00,  7.01it/s]


Correct Classified: 228061.0 / 289972
Class-wise correct: Class 0 = 122657.0, Class 1 = 41097.0, Class 2 = 64307.0
Train Loss after epoch 14: 1.4841054763996004 Train ACC after epoch 12: 0.7864931786517319


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [03:51<00:00, 323.25it/s]


Correct classified: 57521.0 / 74774
Class-wise correct: Class 0 = 32643.0, Class 1 = 9381.0, Class 2 = 15497.0
Precision: 72.82  Recall: 74.13  F1: 72.66
Confusion Matrix:
 [[32643  1874  2046]
 [ 1443  9381  2348]
 [ 2672  6870 15497]]
VAL Loss after epoch 12: 0.6880448776501711 VAL ACC after epoch 12: 0.769264717682617
Test Loss after epoch 12: 0.6880448776501711 Test Acc after epoch 12: 0.769264717682617


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [10:55<00:00,  6.91it/s]


Correct Classified: 228186.0 / 289972
Class-wise correct: Class 0 = 122717.0, Class 1 = 41220.0, Class 2 = 64249.0
Train Loss after epoch 15: 1.4831747260216819 Train ACC after epoch 13: 0.7869242547556315


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:30<00:00, 276.27it/s]


Correct classified: 57813.0 / 74774
Class-wise correct: Class 0 = 32125.0, Class 1 = 8760.0, Class 2 = 16928.0
Precision: 72.61  Recall: 73.99  F1: 72.92
Confusion Matrix:
 [[32125  1781  2657]
 [ 1437  8760  2975]
 [ 1723  6388 16928]]
VAL Loss after epoch 13: 0.6714695632624333 VAL ACC after epoch 13: 0.77316981838607
Test Loss after epoch 13: 0.6714695632624333 Test Acc after epoch 13: 0.77316981838607


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:54<00:00,  6.34it/s]


Correct Classified: 228622.0 / 289972
Class-wise correct: Class 0 = 122838.0, Class 1 = 41486.0, Class 2 = 64298.0
Train Loss after epoch 16: 1.48132354101317 Train ACC after epoch 14: 0.7884278482060337


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:52<00:00, 255.99it/s]


Correct classified: 58009.0 / 74774
Class-wise correct: Class 0 = 32307.0, Class 1 = 9750.0, Class 2 = 15952.0
Precision: 73.70  Recall: 75.36  F1: 73.59
Confusion Matrix:
 [[32307  2093  2163]
 [ 1333  9750  2089]
 [ 2035  7052 15952]]
VAL Loss after epoch 14: 0.6761279007734362 VAL ACC after epoch 14: 0.7757910503651002
Test Loss after epoch 14: 0.6761279007734362 Test Acc after epoch 14: 0.7757910503651002


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:21<00:00,  6.65it/s]


Correct Classified: 228809.0 / 289972
Class-wise correct: Class 0 = 122792.0, Class 1 = 41454.0, Class 2 = 64563.0
Train Loss after epoch 17: 1.4801730120900292 Train ACC after epoch 15: 0.7890727380574676


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:55<00:00, 252.78it/s]


Correct classified: 57857.0 / 74774
Class-wise correct: Class 0 = 32162.0, Class 1 = 9096.0, Class 2 = 16599.0
Precision: 72.92  Recall: 74.44  F1: 73.12
Confusion Matrix:
 [[32162  1888  2513]
 [ 1447  9096  2629]
 [ 1743  6697 16599]]
VAL Loss after epoch 15: 0.673951689789721 VAL ACC after epoch 15: 0.7737582582180972
Test Loss after epoch 15: 0.673951689789721 Test Acc after epoch 15: 0.7737582582180972


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [12:57<00:00,  5.83it/s]


Correct Classified: 228706.0 / 289972
Class-wise correct: Class 0 = 122865.0, Class 1 = 41415.0, Class 2 = 64426.0
Train Loss after epoch 18: 1.4803232819637804 Train ACC after epoch 16: 0.7887175313478543


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [06:04<00:00, 205.16it/s]


Correct classified: 57775.0 / 74774
Class-wise correct: Class 0 = 32569.0, Class 1 = 8813.0, Class 2 = 16393.0
Precision: 72.69  Recall: 73.82  F1: 72.78
Confusion Matrix:
 [[32569  1711  2283]
 [ 1722  8813  2637]
 [ 2146  6500 16393]]
VAL Loss after epoch 16: 0.6736328143092474 VAL ACC after epoch 16: 0.7726616203493193
Test Loss after epoch 16: 0.6736328143092474 Test Acc after epoch 16: 0.7726616203493193


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [11:57<00:00,  6.32it/s]


Correct Classified: 228889.0 / 289972
Class-wise correct: Class 0 = 122890.0, Class 1 = 41579.0, Class 2 = 64420.0
Train Loss after epoch 19: 1.4787098587914245 Train ACC after epoch 17: 0.7893486267639634


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [07:30<00:00, 166.04it/s]


Correct classified: 57665.0 / 74774
Class-wise correct: Class 0 = 32497.0, Class 1 = 9386.0, Class 2 = 15782.0
Precision: 72.96  Recall: 74.39  F1: 72.86
Confusion Matrix:
 [[32497  1909  2157]
 [ 1445  9386  2341]
 [ 2205  7052 15782]]
VAL Loss after epoch 17: 0.6844763239042475 VAL ACC after epoch 17: 0.7711905207692513
Test Loss after epoch 17: 0.6844763239042475 Test Acc after epoch 17: 0.7711905207692513


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [12:49<00:00,  5.88it/s]


Correct Classified: 228746.0 / 289972
Class-wise correct: Class 0 = 122767.0, Class 1 = 41524.0, Class 2 = 64455.0
Train Loss after epoch 20: 1.4781576973059087 Train ACC after epoch 18: 0.7888554757011021


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [05:43<00:00, 217.44it/s]


Correct classified: 57757.0 / 74774
Class-wise correct: Class 0 = 32138.0, Class 1 = 9374.0, Class 2 = 16245.0
Precision: 72.98  Recall: 74.65  F1: 73.10
Confusion Matrix:
 [[32138  2073  2352]
 [ 1194  9374  2604]
 [ 1917  6877 16245]]
VAL Loss after epoch 18: 0.6801091985903615 VAL ACC after epoch 18: 0.77242089496349
Test Loss after epoch 18: 0.6801091985903615 Test Acc after epoch 18: 0.77242089496349


Training:   0%|          | 0/4531 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Training: 100%|██████████| 4531/4531 [13:00<00:00,  5.80it/s]


Correct Classified: 229064.0 / 289972
Class-wise correct: Class 0 = 122854.0, Class 1 = 41668.0, Class 2 = 64542.0
Train Loss after epoch 21: 1.476430105889404 Train ACC after epoch 19: 0.7899521333094229


Eval:   0%|          | 0/74774 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ca5e669e160>
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/anaconda/anaconda3/envs/braindecode/lib/python3.8/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 74774/74774 [04:38<00:00, 268.19it/s]


Correct classified: 57582.0 / 74774
Class-wise correct: Class 0 = 32204.0, Class 1 = 8377.0, Class 2 = 17001.0
Precision: 72.03  Recall: 73.19  F1: 72.33
Confusion Matrix:
 [[32204  1674  2685]
 [ 1558  8377  3237]
 [ 1687  6351 17001]]
VAL Loss after epoch 19: 0.6730931515704761 VAL ACC after epoch 19: 0.7700805092679274
Test Loss after epoch 19: 0.6730931515704761 Test Acc after epoch 19: 0.7700805092679274


In [8]:
print("Epoch | Train Loss | Train Acc | Eval Loss | Eval Acc | Test Loss | Test Acc  ")
for epoch in range(epochs):
    if(saved_epoch == epoch):
        print("Saved Weights")
    print(result['epoch'][epoch],"|",result['train_loss'][epoch],"|",result['train_acc'][epoch],"|",result['eval_loss'][epoch],"|",result['eval_acc'][epoch],"|",result['test_loss'][epoch],"|",result['test_acc'][epoch])

Epoch | Train Loss | Train Acc | Eval Loss | Eval Acc | Test Loss | Test Acc  
0 | 1.7260208891285778 | 0.6514491054308692 | 0.7670723067209797 | 0.7248508839971113 | 0.7670723067209797 | 0.7248508839971113
1 | 1.5908155940642448 | 0.7269081152663016 | 0.7135739833962287 | 0.7534035894829754 | 0.7135739833962287 | 0.7534035894829754
2 | 1.5565125984851953 | 0.7479998068779055 | 0.6948183821042198 | 0.7721534223125686 | 0.6948183821042198 | 0.7721534223125686
3 | 1.5379551311540067 | 0.75935952436787 | 0.6906158838526826 | 0.7698932784122824 | 0.6906158838526826 | 0.7698932784122824
4 | 1.5248508161594472 | 0.7669947443201413 | 0.6905913419630342 | 0.7680744643860166 | 0.6905913419630342 | 0.7680744643860166
5 | 1.5150250786583672 | 0.7709158125612128 | 0.6722244736536854 | 0.7795356674780004 | 0.6722244736536854 | 0.7795356674780004
6 | 1.5071563393673448 | 0.7746058240105941 | 0.6668107484041087 | 0.7737983791157355 | 0.6668107484041087 | 0.7737983791157355
Saved Weights
7 | 1.5013121

In [9]:
model_state_dict = torch.load(model_saving_name)
# Load the state_dict into the model
model.load_state_dict(model_state_dict)
eval_loss, eval_acc = eval(model, val_loader, loss_fn, eval_batch,True,prediction_saving_csv_eval, active_branches, device)
print(f"VAL Loss: {eval_loss} VAL ACC: {eval_acc}")

# eval_loss, eval_acc = eval(model, train_loader, loss_fn, eval_batch,True,prediction_saving_csv_train)
# print(f"Train Loss: {eval_loss} Train ACC: {eval_acc}")

/tmp/ipykernel_1085736/3846926396.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_state_dict = torch.load(model_saving_name)
Eval:   0%|          | 0/43343 [00:00<

/media/dll-1/SSD 4TB/code/eeg_classifiers/EEDDataLoader.py:59: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  wavelet_transform = torch.tensor(coefficients_cmor, dtype=torch.float32)
Eval: 100%|██████████| 43343/43343 [02:46<00:00, 261.05it/s]


Correct classified: 34390.0 / 43343
Class-wise correct: Class 0 = 18985.0, Class 1 = 11345.0, Class 2 = 4060.0
Precision: 73.76  Recall: 76.50  F1: 74.25
Confusion Matrix:
 [[18985  1455  2098]
 [ 1047 11345  2564]
 [ 1451   338  4060]]
VAL Loss: 0.6613021071443229 VAL ACC: 0.7934383868214013
